### ISSUE TITLE
`aqua g -i` failed when a comment exists in the same line with `packages:`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2245]
### aqua info

```console
$ aqua info
{
  "version": "2.10.1",
  "commit_hash": "fbf3b157b21897fa2f315fbc30474acafded108d",
  "os": "linux",
  "arch": "arm64",
  "pwd": "/workspace",
  "root_dir": "/(USER)/.local/share/aquaproj-aqua",
  "env": {},
  "config_files": [
    {
      "path": "/workspace/aqua.yaml"
    }
  ]
}
```

### Overview

`aqua g -i` failed when a comment exists in the same line with `packages:`

e.g.

aqua.yaml

```yaml
packages: # foo
```

```console
$ aqua g -i cli/cli
FATA[0000] aqua failed                                   aqua_version=2.10.1 env=linux/arm64 error="the field 'packages' isn't found" program=aqua
```

### How to reproduce

aqua.yaml

```yaml
registries:
- type: standard
  ref: v4.48.1
packages: # foo
```

Executed command and output

```console
$ aqua g -i cli/cli
FATA[0000] aqua failed                                   aqua_version=2.10.1 env=linux/arm64 error="the field 'packages' isn't found" program=aqua
```

### Debug output

```console
$ aqua -log-level debug g -i cli/cli
FATA[0000] aqua failed                                   aqua_version=2.10.1 env=linux/arm64 error="the field 'packages' isn't found" program=aqua
```

### Expected behaviour

Packages are added to aqua.yaml.

### Actual behaviour

The command `aqua g -i` fails and packages aren't added to aqua.yaml.

### Important Factoids

`aqua g -i` parses aqua.yaml with https://github.com/goccy/go-yaml and treats AST.

https://github.com/aquaproj/aqua/blob/ad8dfe313e36053d75c80d11b7ca771938788080/pkg/controller/generate/output/insert.go#L92-L95

https://github.com/aquaproj/aqua/blob/ad8dfe313e36053d75c80d11b7ca771938788080/pkg/controller/generate/output/insert.go#L46-L54

**Comment by suzuki-shunsuke** [comment]
The similar error.

aqua.yaml

```yaml
registries:
- type: standard
  ref: v4.48.1
packages:
# foo
```

```console
$ aqua g -i cli/cli
FATA[0000] aqua failed                                   aqua_version=2.10.1 env=linux/arm64 error="packages must be null or array" program=aqua
```

https://github.com/aquaproj/aqua/blob/ad8dfe313e36053d75c80d11b7ca771938788080/pkg/controller/generate/output/insert.go#L66-L79

https://github.com/aquaproj/aqua/blob/ad8dfe313e36053d75c80d11b7ca771938788080/pkg/controller/generate/output/insert.go#L97

**Comment by suzuki-shunsuke** [comment]
Hmm. As a result of the debug, I found `mapValue.Key.String()` returns `packages # foo`.
Is this a bug of `go-yaml`? 🤔

**Comment by suzuki-shunsuke** [comment]
`mapValue.Key.String()` is wrong.
We should use `*ast.StringNode.Value` instead.

**Comment by suzuki-shunsuke** [comment]
test

**Comment by suzuki-shunsuke** [comment]
aqua.yaml

```yaml
registries:
- type: standard
  ref: v4.48.1
packages:
# foo
```

```console
$ aqua -v
aqua version 2.14.0 (3ba4016fef92658ae78144918e25027dea529dce)
```

```console
$ aqua g -i cli/cli
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x100d7b3a0]

goroutine 1 [running]:
github.com/goccy/go-yaml/parser.(*parser).createMapValueNode(0x14001058818?, 0x14000c1b0c0, {0x1013f8978, 0x140009d0680}, 0x14000e565a0)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:167 +0x140
github.com/goccy/go-yaml/parser.(*parser).parseMapValue(0x14000c1aa80?, 0x14000c1b0c0, {0x1013f8978?, 0x140009d0680?}, 0x14000f67460?)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:142 +0x28
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xb?, 0x14000c1aa80)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:258 +0x170
github.com/goccy/go-yaml/parser.(*parser).createNodeFromToken(0x14001058a08?, 0x14000e9e770?, 0x1?)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:647 +0x2d0
github.com/goccy/go-yaml/parser.(*parser).parseToken(0x14000c1aa80?, 0x14000c1aa80, 0xa?)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:632 +0x20
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0x7?, 0x14000c1aa80)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:276 +0x794
github.com/goccy/go-yaml/parser.(*parser).createNodeFromToken(0x30?, 0x14000080900?, 0x14000f730e0?)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:647 +0x2d0
github.com/goccy/go-yaml/parser.(*parser).parseToken(0x10131e500?, 0x14000c1aa80, 0x14001058c58?)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:632 +0x20
github.com/goccy/go-yaml/parser.(*parser).parse(0x0?, {0x14000b72280?, 0x0?, 0x1?}, 0x0?)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:688 +0x114
github.com/goccy/go-yaml/parser.Parse({0x14000b72280?, 0x14000440000?, 0x3c?}, 0x0?)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:724 +0x34
github.com/goccy/go-yaml/parser.ParseBytes({0x14000440000?, 0x101ac2500?, 0x14000037c40?}, 0x10102f4d0?)
	/home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/parser/parser.go:714 +0x3c
github.com/aquaproj/aqua/v2/pkg/controller/generate/output.(*Outputter).generateInsert(0x14000375ec0, {0x14000037c40, 0x3a}, {0x14000e28020, 0x1, 0x1})
	/home/runner/work/aqua/aqua/pkg/controller/generate/output/insert.go:21 +0xa4
github.com/aquaproj/aqua/v2/pkg/controller/generate/output.(*Outputter).Output(0x14000363860?, 0x14000c1aa00)
	/home/runner/work/aqua/aqua/pkg/controller/generate/output/output.go:41 +0x3e4
github.com/aquaproj/aqua/v2/pkg/controller/generate.(*Controller).Generate(0x14000363860, {0x1013f3ba0, 0x14000045d80}, 0x101a8afc0?, 0x1400037c780, {0x140003a12d0, 0x1, 0x1})
	/home/runner/work/aqua/aqua/pkg/controller/generate/generate.go:56 +0x1e8
github.com/aquaproj/aqua/v2/pkg/cli.(*Runner).generateAction(0x14000108ff0, 0x140003a21c0)
	/home/runner/work/aqua/aqua/pkg/cli/generate.go:164 +0x1dc
github.com/urfave/cli/v2.(*Command).Run(0x140002caf20, 0x140003a21c0, {0x14000373950, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x730
github.com/urfave/cli/v2.(*Command).Run(0x1400039e420, 0x14000045f40, {0x140000301e0, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 +0x940
github.com/urfave/cli/v2.(*App).RunContext(0x1400035e5a0, {0x1013f3ba0?, 0x14000045d80}, {0x140000301e0, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x518
github.com/aquaproj/aqua/v2/pkg/cli.(*Runner).Run(0x14000108ff0, {0x1013f3ba0, 0x14000045d80}, {0x140000301e0, 0x6, 0x6})
	/home/runner/work/aqua/aqua/pkg/cli/runner.go:181 +0x28a4
main.core(0x140003208c0, 0x14000374680)
	/home/runner/work/aqua/aqua/cmd/aqua/main.go:56 +0x228
main.main()
	/home/runner/work/aqua/aqua/cmd/aqua/main.go:30 +0x48
```
