### ISSUE TITLE
`aqua update` starts to fail with SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by tadayosi** [aquaproj/aqua#2764]
### aqua info

```console
$ aqua info
{
  "version": "2.25.0",
  "commit_hash": "3f367c2f7f9fcebe270c0c02d496d6ca962321bc",
  "os": "darwin",
  "arch": "arm64",
  "pwd": "/Users/(USER)",
  "root_dir": "/Users/(USER)/.local/share/aquaproj-aqua",
  "env": {
    "GITHUB_TOKEN": "(masked)"
  },
  "config_files": [
    {
      "path": "/Users/(USER)/.aqua.yaml"
    }
  ]
}
```

### Overview

`aqua update` starts to fail for me.

### How to reproduce

aqua.yaml

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.147.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: aandrew-me/tgpt@v2.7.1
- name: ahmetb/kubectx/kubens@v0.9.5
- name: ahmetb/kubectx@v0.9.5
- name: apache/maven-mvnd@1.0-m8
- name: charmbracelet/glow@v1.5.1
- name: cli/cli@v2.44.1
- name: derailed/k9s@v0.32.3
- name: direnv/direnv@v2.34.0
- name: jqlang/jq@jq-1.7.1
- name: kubernetes/kubectl@v1.29.2
- name: kubernetes/minikube@v1.32.0
- name: mikefarah/yq@v4.42.1
- name: neovim/neovim@v0.9.5
- name: sharkdp/bat@v0.24.0
- name: snyk/cli@v1.1285.0
- name: stern/stern@v1.28.0
```

Other related code such as local Registry

n/a

Executed command and output

```console
$ aqua update
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1027fc828]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).Prerelease(...)
	/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:332
github.com/aquaproj/aqua/v2/pkg/versiongetter.convRelease(0x14000bd6180)
	/home/runner/work/aqua/aqua/pkg/versiongetter/github_release.go:45 +0x58
github.com/aquaproj/aqua/v2/pkg/versiongetter.(*GitHubReleaseVersionGetter).Get(0x14000332710, {0x102bbc180, 0x14000051280}, 0x3ad7dba8?, 0x3ad7dba800000000?, {0x14000aa9cb0, 0x2, 0x2})
	/home/runner/work/aqua/aqua/pkg/versiongetter/github_release.go:110 +0x22c
github.com/aquaproj/aqua/v2/pkg/versiongetter.(*GeneralVersionGetter).Get(0x14000a717a0?, {0x102bbc180?, 0x14000051280?}, 0xa?, 0x14000614888?, {0x14000aa9cb0?, 0x102a52c80?, 0xc?})
	/home/runner/work/aqua/aqua/pkg/versiongetter/general.go:33 +0xf8
github.com/aquaproj/aqua/v2/pkg/versiongetter.(*FuzzyGetter).Get(0x14000334da0, {0x102bbc180, 0x14000051280}, 0x14000a717a0, 0x140009346c8, {0x140006e8b96, 0x6}, 0x0, 0x1e)
	/home/runner/work/aqua/aqua/pkg/versiongetter/fuzzy_getter.go:73 +0x348
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).getPackageNewVersion(0x14000427dc0?, {0x102bbc180?, 0x14000051280?}, 0x8?, 0x2?, 0x1400054194e?, 0x14000132180?)
	/home/runner/work/aqua/aqua/pkg/controller/update/package.go:88 +0x1f8
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).updatePackagesInFile(0x140001292c0, {0x102bbc180, 0x14000051280}, 0x14000427dc0, 0x1400032a6e0, {0x140001c9120, 0x1a}, 0x0?, 0x0?, 0x1400004aff8, ...)
	/home/runner/work/aqua/aqua/pkg/controller/update/package.go:65 +0x2b0
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).updatePackages(0x140001292c0, {0x102bbc180, 0x14000051280}, 0x14000427dc0, 0x1400032a6e0, {0x140001c9120, 0x1a}, 0x14000119bc0)
	/home/runner/work/aqua/aqua/pkg/controller/update/package.go:38 +0x254
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).update(0x140001292c0, {0x102bbc180, 0x14000051280}, 0x14000427dc0, 0x1400032a6e0, {0x140001c9120, 0x1a})
	/home/runner/work/aqua/aqua/pkg/controller/update/update.go:107 +0x364
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).Update(0x140001292c0, {0x102bbc180, 0x14000051280}, 0x14000427dc0, 0x1400032a6e0)
	/home/runner/work/aqua/aqua/pkg/controller/update/update.go:28 +0xd0
github.com/aquaproj/aqua/v2/pkg/cli.(*Runner).updateAction(0x14000098a50, 0x14000134d00)
	/home/runner/work/aqua/aqua/pkg/cli/update.go:140 +0x194
github.com/urfave/cli/v2.(*Command).Run(0x1400032a160, 0x14000134d00, {0x1400011fd30, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x71c
github.com/urfave/cli/v2.(*Command).Run(0x1400032a420, 0x14000134a00, {0x14000140000, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0x918
github.com/urfave/cli/v2.(*App).RunContext(0x140002f6400, {0x102bbc180, 0x14000051280}, {0x14000140000, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x514
github.com/aquaproj/aqua/v2/pkg/cli.(*Runner).Run(0x14000098a50, {0x102bbc180, 0x14000051280}, {0x14000140000, 0x2, 0x2})
	/home/runner/work/aqua/aqua/pkg/cli/runner.go:199 +0x2658
main.core(0x14000427dc0, 0x14000030960)
	/home/runner/work/aqua/aqua/cmd/aqua/main.go:56 +0x228
main.main()
	/home/runner/work/aqua/aqua/cmd/aqua/main.go:30 +0x48
```

### Debug output

```console
$ AQUA_LOG_LEVEL=debug aqua update
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=aandrew-me/tgpt package_semver=v2.7.1 package_version=v2.7.1 program=aqua registry=standard registry_ref=v4.147.0 version_constraint=true
DEBU[0000] no version_constraint                         aqua_version=2.25.0 env=darwin/arm64 package_name=ahmetb/kubectx/kubens package_version=v0.9.5 program=aqua registry=standard registry_ref=v4.147.0
DEBU[0000] no version_constraint                         aqua_version=2.25.0 env=darwin/arm64 package_name=ahmetb/kubectx package_version=v0.9.5 program=aqua registry=standard registry_ref=v4.147.0
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=apache/maven-mvnd package_semver=1.0-m8 package_version=1.0-m8 program=aqua registry=standard registry_ref=v4.147.0 version_constraint=true
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=charmbracelet/glow package_semver=v1.5.1 package_version=v1.5.1 program=aqua registry=standard registry_ref=v4.147.0 version_constraint="semver(\">= 1.5.1\")"
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=cli/cli package_semver=v2.44.1 package_version=v2.44.1 program=aqua registry=standard registry_ref=v4.147.0 version_constraint=true
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=derailed/k9s package_semver=v0.32.3 package_version=v0.32.3 program=aqua registry=standard registry_ref=v4.147.0 version_constraint=true
DEBU[0000] no version_constraint                         aqua_version=2.25.0 env=darwin/arm64 package_name=direnv/direnv package_version=v2.34.0 program=aqua registry=standard registry_ref=v4.147.0
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=jqlang/jq package_semver=1.7.1 package_version=jq-1.7.1 program=aqua registry=standard registry_ref=v4.147.0 version_constraint="semver(\">= 1.7rc1\")"
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=kubernetes/kubectl package_semver=v1.29.2 package_version=v1.29.2 program=aqua registry=standard registry_ref=v4.147.0 version_constraint="semver(\">= 1.23.0\")"
DEBU[0000] no version_constraint                         aqua_version=2.25.0 env=darwin/arm64 package_name=kubernetes/minikube package_version=v1.32.0 program=aqua registry=standard registry_ref=v4.147.0
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=mikefarah/yq package_semver=v4.42.1 package_version=v4.42.1 program=aqua registry=standard registry_ref=v4.147.0 version_constraint="semver(\">= 4.9.6\")"
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=neovim/neovim package_semver=v0.9.5 package_version=v0.9.5 program=aqua registry=standard registry_ref=v4.147.0 version_constraint="semver(\">= 0.7.2\")"
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=sharkdp/bat package_semver=v0.24.0 package_version=v0.24.0 program=aqua registry=standard registry_ref=v4.147.0 version_constraint=true
DEBU[0000] no version_constraint                         aqua_version=2.25.0 env=darwin/arm64 package_name=snyk/cli package_version=v1.1285.0 program=aqua registry=standard registry_ref=v4.147.0
DEBU[0000] match the version_constraint                  aqua_version=2.25.0 env=darwin/arm64 package_name=stern/stern package_semver=v1.28.0 package_version=v1.28.0 program=aqua registry=standard registry_ref=v4.147.0 version_constraint="semver(\">= 1.21.0\")"
DEBU[0001] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4963 package_name=aandrew-me/tgpt package_version=v2.7.1 program=aqua registry=standard repository=aandrew-me/tgpt
DEBU[0001] retrieve package versions in 1.180526583s     aqua_version=2.25.0 env=darwin/arm64 package_name=aandrew-me/tgpt package_version=v2.7.1 program=aqua registry=standard repository=aandrew-me/tgpt
DEBU[0001] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4962 package_name=ahmetb/kubectx/kubens package_version=v0.9.5 program=aqua registry=standard repository=ahmetb/kubectx
DEBU[0001] retrieve package versions in 466.354875ms     aqua_version=2.25.0 env=darwin/arm64 package_name=ahmetb/kubectx/kubens package_version=v0.9.5 program=aqua registry=standard repository=ahmetb/kubectx
DEBU[0002] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4961 package_name=ahmetb/kubectx package_version=v0.9.5 program=aqua registry=standard repository=ahmetb/kubectx
DEBU[0002] retrieve package versions in 426.242333ms     aqua_version=2.25.0 env=darwin/arm64 package_name=ahmetb/kubectx package_version=v0.9.5 program=aqua registry=standard repository=ahmetb/kubectx
DEBU[0002] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4960 package_name=apache/maven-mvnd package_version=1.0-m8 program=aqua registry=standard repository=apache/maven-mvnd
DEBU[0002] retrieve package versions in 711.905709ms     aqua_version=2.25.0 env=darwin/arm64 package_name=apache/maven-mvnd package_version=1.0-m8 program=aqua registry=standard repository=apache/maven-mvnd
DEBU[0003] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4959 package_name=charmbracelet/glow package_version=v1.5.1 program=aqua registry=standard repository=charmbracelet/glow
DEBU[0003] retrieve package versions in 618.27225ms      aqua_version=2.25.0 env=darwin/arm64 package_name=charmbracelet/glow package_version=v1.5.1 program=aqua registry=standard repository=charmbracelet/glow
DEBU[0004] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4958 package_name=cli/cli package_version=v2.44.1 program=aqua registry=standard repository=cli/cli
DEBU[0004] retrieve package versions in 936.893584ms     aqua_version=2.25.0 env=darwin/arm64 package_name=cli/cli package_version=v2.44.1 program=aqua registry=standard repository=cli/cli
DEBU[0005] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4957 package_name=derailed/k9s package_version=v0.32.3 program=aqua registry=standard repository=derailed/k9s
DEBU[0005] retrieve package versions in 1.02920975s      aqua_version=2.25.0 env=darwin/arm64 package_name=derailed/k9s package_version=v0.32.3 program=aqua registry=standard repository=derailed/k9s
DEBU[0006] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4956 package_name=direnv/direnv package_version=v2.34.0 program=aqua registry=standard repository=direnv/direnv
DEBU[0006] retrieve package versions in 739.026125ms     aqua_version=2.25.0 env=darwin/arm64 package_name=direnv/direnv package_version=v2.34.0 program=aqua registry=standard repository=direnv/direnv
DEBU[0006] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4955 package_name=jqlang/jq package_version=jq-1.7.1 program=aqua registry=standard repository=jqlang/jq
DEBU[0006] retrieve package versions in 563.45175ms      aqua_version=2.25.0 env=darwin/arm64 package_name=jqlang/jq package_version=jq-1.7.1 program=aqua registry=standard repository=jqlang/jq
DEBU[0007] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4954 package_name=kubernetes/kubectl package_version=v1.29.2 program=aqua registry=standard repository=kubernetes/kubernetes
DEBU[0007] retrieve package versions in 501.763416ms     aqua_version=2.25.0 env=darwin/arm64 package_name=kubernetes/kubectl package_version=v1.29.2 program=aqua registry=standard repository=kubernetes/kubernetes
DEBU[0008] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4953 package_name=kubernetes/minikube package_version=v1.32.0 program=aqua registry=standard repository=kubernetes/minikube
DEBU[0008] retrieve package versions in 1.22974975s      aqua_version=2.25.0 env=darwin/arm64 package_name=kubernetes/minikube package_version=v1.32.0 program=aqua registry=standard repository=kubernetes/minikube
DEBU[0009] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4952 package_name=mikefarah/yq package_version=v4.42.1 program=aqua registry=standard repository=mikefarah/yq
DEBU[0009] retrieve package versions in 1.042624417s     aqua_version=2.25.0 env=darwin/arm64 package_name=mikefarah/yq package_version=v4.42.1 program=aqua registry=standard repository=mikefarah/yq
DEBU[0010] GitHub API Rate Limit info                    aqua_version=2.25.0 env=darwin/arm64 github_api_rate_limit=5000 github_api_rate_remaining=4951 package_name=neovim/neovim package_version=v0.9.5 program=aqua registry=standard repository=neovim/neovim
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1054dc828]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).Prerelease(...)
	/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:332
github.com/aquaproj/aqua/v2/pkg/versiongetter.convRelease(0x14000ade180)
	/home/runner/work/aqua/aqua/pkg/versiongetter/github_release.go:45 +0x58
github.com/aquaproj/aqua/v2/pkg/versiongetter.(*GitHubReleaseVersionGetter).Get(0x1400050a710, {0x10589c180, 0x1400012d240}, 0x12c3c988?, 0x12c3c98800000000?, {0x14000b27e50, 0x2, 0x2})
	/home/runner/work/aqua/aqua/pkg/versiongetter/github_release.go:110 +0x22c
github.com/aquaproj/aqua/v2/pkg/versiongetter.(*GeneralVersionGetter).Get(0x14000a9b8f0?, {0x10589c180?, 0x1400012d240?}, 0xa?, 0x140005b4888?, {0x14000b27e50?, 0x105732c80?, 0xc?})
	/home/runner/work/aqua/aqua/pkg/versiongetter/general.go:33 +0xf8
github.com/aquaproj/aqua/v2/pkg/versiongetter.(*FuzzyGetter).Get(0x1400050cac0, {0x10589c180, 0x1400012d240}, 0x14000a9b8f0, 0x140008b6fc8, {0x140006f2bae, 0x6}, 0x0, 0x1e)
	/home/runner/work/aqua/aqua/pkg/versiongetter/fuzzy_getter.go:73 +0x348
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).getPackageNewVersion(0x1400043ddc0?, {0x10589c180?, 0x1400012d240?}, 0x8?, 0x2?, 0x140005d595e?, 0x14000130660?)
	/home/runner/work/aqua/aqua/pkg/controller/update/package.go:88 +0x1f8
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).updatePackagesInFile(0x1400045e5a0, {0x10589c180, 0x1400012d240}, 0x1400043ddc0, 0x1400047a6e0, {0x1400011c820, 0x1a}, 0x0?, 0x0?, 0x1400004aff8, ...)
	/home/runner/work/aqua/aqua/pkg/controller/update/package.go:65 +0x2b0
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).updatePackages(0x1400045e5a0, {0x10589c180, 0x1400012d240}, 0x1400043ddc0, 0x1400047a6e0, {0x1400011c820, 0x1a}, 0x14000466b10)
	/home/runner/work/aqua/aqua/pkg/controller/update/package.go:38 +0x254
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).update(0x1400045e5a0, {0x10589c180, 0x1400012d240}, 0x1400043ddc0, 0x1400047a6e0, {0x1400011c820, 0x1a})
	/home/runner/work/aqua/aqua/pkg/controller/update/update.go:107 +0x364
github.com/aquaproj/aqua/v2/pkg/controller/update.(*Controller).Update(0x1400045e5a0, {0x10589c180, 0x1400012d240}, 0x1400043ddc0, 0x1400047a6e0)
	/home/runner/work/aqua/aqua/pkg/controller/update/update.go:28 +0xd0
github.com/aquaproj/aqua/v2/pkg/cli.(*Runner).updateAction(0x14000126a00, 0x1400012d6c0)
	/home/runner/work/aqua/aqua/pkg/cli/update.go:140 +0x194
github.com/urfave/cli/v2.(*Command).Run(0x1400047a160, 0x1400012d6c0, {0x14000123d30, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x71c
github.com/urfave/cli/v2.(*Command).Run(0x1400047a420, 0x1400012d3c0, {0x14000030040, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0x918
github.com/urfave/cli/v2.(*App).RunContext(0x14000448400, {0x10589c180, 0x1400012d240}, {0x14000030040, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x514
github.com/aquaproj/aqua/v2/pkg/cli.(*Runner).Run(0x14000126a00, {0x10589c180, 0x1400012d240}, {0x14000030040, 0x2, 0x2})
	/home/runner/work/aqua/aqua/pkg/cli/runner.go:199 +0x2658
main.core(0x1400043ddc0, 0x14000124920)
	/home/runner/work/aqua/aqua/cmd/aqua/main.go:56 +0x228
main.main()
	/home/runner/work/aqua/aqua/cmd/aqua/main.go:30 +0x48

```

### Expected behaviour

The packages in `aqua.yaml` should be updated to the latest versions.

### Actual behaviour

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1027fc828]
```

**Comment by suzuki-shunsuke** [comment]
Thank you for your report!
I'll take a look.

**Comment by suzuki-shunsuke** [comment]
```
github.com/aquaproj/aqua/v2/pkg/versiongetter.convRelease(0x14000bd6180)
	/home/runner/work/aqua/aqua/pkg/versiongetter/github_release.go:45 +0x58
```

https://github.com/aquaproj/aqua/blob/3f367c2f7f9fcebe270c0c02d496d6ca962321bc/pkg/versiongetter/github_release.go#L45

**Comment by suzuki-shunsuke** [comment]
I opened a pull request to resolve the issue.

- https://github.com/aquaproj/aqua/pull/2765

Unfortunately, we couldn't release a new version due to the issue of the release workflow.

- https://github.com/aquaproj/aqua/issues/2759#issuecomment-2009176284
- https://github.com/slsa-framework/slsa-github-generator/issues/3350

I hope the issue would be solved soon.

**Comment by nikolay** [comment]
By the way, I'm experiencing the same error.

**Comment by suzuki-shunsuke** [comment]
v2.25.1 is out 🎉
https://github.com/aquaproj/aqua/releases/tag/v2.25.1

**Comment by tadayosi** [comment]
@suzuki-shunsuke It works, thank you! :tada:
